name: Reportar un bug
description: ¿Has encontrado un error? Repórtalo aquí
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
     value: |
      Muchas gracias de antemano por tu ayuda. Sin embargo, necesitamos una serie de informaciones para poder ayudarte.
  - type: checkboxes
    attributes:
      label: "Lista de verificaciones que debes completar antes de validar el reporte del bug"
      description: Asegúrate de haber completado lo siguiente, de lo contrario, tu reporte podría ser rechazado
      options:
        - label: Puedo reproducir el bug en la última versión
          required: true
  - type: dropdown
    attributes:
      label: Sistema operativo
      options:
        - Windows
        - macOS
        - Linux (Basado en Debian/Ubuntu)
        - Linux (Otros)
    validations:
      required: true
  - type: input
    attributes:
      label: Versión del sistema operativo
      placeholder: "Ejemplo: Windows 11 Profesional 21H2 Build 22000.739"
    validations:
        required: true
  - type: input
    attributes:
      label: Hash del commit donde se encuentra el bug
      placeholder: 84d7881b67ecf6088205eca6723bfb19bf2a5f0d
  - type: textarea
    attributes:
      label: Comportamiento esperado
      description: Una descripción de lo que debería suceder
      placeholder: El launcher debería...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Comportamiento actual
      description: Una descripción de lo que sucede con el bug
    validations:
      required: true
  - type: textarea
    attributes:
      label: Instrucciones para reproducir el bug
      placeholder: |
        1. Abrir el launcher
        2. Ir al menú xyz
        3. Hacer clic en abc
        4. Observar
    validations:
      required: true
  - type: textarea
    attributes:
      label: Notas adicionales
      placeholder: Detalles adicionales sobre el bug, todo lo que pueda ser útil
    validations:
      required: false
