blank_issues_enabled: false
contact_links:
  - name: Únete a nuestro Discord para cualquier pregunta o solicitud
    url: https://discord.comunidadojo.xyz
    about: Por favor, no abras un issue que no sea para reportar errores
